### ISSUE TITLE
Updating character stats on pages

### ISSUE THREAD

**Issue by LinkXXI** [LinkXXI/C--Final-Project#1]
We need to find a way to update the stats on the bottom of the page when something happens.

The page has a property called Master that returns the master page and it should be able to have a control selected out of it but I've had no luck so far.

**Comment by LinkXXI** [comment]
Fixed by adding a listener to preRender on the master page, setting the data to the label.

**Comment by AaronPersonal** [comment]
Here is the writeup, its kinda empty but theres not much to say
